platform :ios, '8.0'

target 'KeepHappy' do
use_frameworks!

pod "AFNetworking"
pod "SDWebImage"
pod "YYModel"
pod "FMDB"
pod "SVProgressHUD"
pod "MJRefresh"

pod "UMengUShare/UI"
pod "UMengUShare/Social/ReducedWeChat"
pod "UMengAnalytics-NO-IDFA"

end
