platform :ios, '8.0'

target 'KeepHappy' do
use_frameworks!

pod "AFNetworking"
pod "SDWebImage"
pod "YYModel"
pod "FMDB"
pod "SVProgressHUD"
pod "UMengUShare/UI"
pod "UMengUShare/Social/ReducedWeChat"

end
